# Generated by Django 3.1.5 on 2021-01-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Informatica'), ('4', 'Base de datos'), ('5', 'Otro')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
